# [LIST],(TUPLE),{SET} and DICTIONARY

# List

In [1]:
list1=[1,2,3,4,5]

In [2]:
list1


[1, 2, 3, 4, 5]

In [3]:
list2=[5,6,7,8,9]

In [4]:
list2

[5, 6, 7, 8, 9]

In [5]:
list3=list1+list2

In [6]:
list3

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]

In [7]:
len(list3)

10

# Numpy

In [8]:
import numpy as np

In [9]:
a = np.arange(5)

In [10]:
a

array([0, 1, 2, 3, 4])

In [11]:
a.ndim

1

In [12]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a.dtype

dtype('int64')

In [14]:
a.dtype.name

'int64'

In [15]:
np.array([[1,2],[3,4]],dtype=complex)

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
num = np.array([3+2.j])

In [21]:
num.dtype

dtype('complex128')

## Set

In [1]:
set1={1,2}

In [2]:
set1

{1, 2}

In [4]:
{2 in set1}

{True}

In [5]:
# Cartesian Product
def cartesianproduct(S1,S2):
    result=set()
    for i in S1:
        for j in S2:
            result.add(tuple([i,j]))
    return result

In [7]:
cartesianproduct({'A','B','C'},{1,2,3})

{('A', 1),
 ('A', 2),
 ('A', 3),
 ('B', 1),
 ('B', 2),
 ('B', 3),
 ('C', 1),
 ('C', 2),
 ('C', 3)}